"""
Django settings for TimeTrack project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w3oi^3ucsf_qkk$4bm^xds3z*p&xjmy^-)9m%6tp^y+u7o#xd%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# redirects when these events occur
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = 'myaccount'
LOGOUT_REDIRECT_URL = 'frontpage'

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = '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'
EMAIL_PORT = 465
EMAIL_USE_TLS = True
DEFAULT_EMAIL_FROM = 'sehrishwaheed30@gmail.com'

WEBSITE_URL = 'http://127.0.0.1:8000'
ACCEPTATION_URL = WEBSITE_URL + '/signup/'

SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')

ALLOWED_HOSTS = []

STRIPE_PUBLISHABLE_KEY = 'pk_test_51HSUY0AdvemoYxG9xgzcDDUzNF3YrhNkBrTtIaBHDta61z9MAPfQ4uXzj0OWGrL30p2bYM6nkSmoqfAUjec2BRlw00WMx5fgtF'
STRIPE_SECRET_KEY = 'sk_test_51HSUY0AdvemoYxG9pNxwFUdSvEgdTi3jHDOX9GiGmnImdfUgIjn4h12tYMF7El6ZiI3lJ6SpUgxiUIgOaKCiXFnu00XGn6UMys'
STRIPE_BASIC_PRICE_ID = 'price_1IFK8FAdvemoYxG960w1nlDI'
STRIPE_PRO_PRICE_ID = 'price_1IFK8yAdvemoYxG9i2gllQx8'

# stripe listen --forward-to localhost:8000/dashboard/myaccount/teams/api/stripe_webhook/
STRIPE_WEBHOOK_KEY = 'whsec_JGqspg3q54zRAREE2RPsmtlYCdMyWXFf'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.core',
    'apps.project',
    'apps.userprofile',
    'apps.team',
    'apps.dashboard',

    'sass_processor',
    'fontawesome_5'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TimeTrack.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.team.context_processors.active_team',
                'apps.project.context_processors.active_entry',
            ],
        },
    },
]

WSGI_APPLICATION = 'TimeTrack.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# STATIC_ROOT = BASE_DIR / 'static'

# SASS_PROCESSOR_ROOT = STATIC_ROOT

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
# STATICFILES_FINDERS = [
#     'django.contrib.staticfiles.finders.FileSystemFinder',
#     'django.contrib.staticfiles.finders.AppDirectoriesFinder',
#     'sass_processor.finders.CssFinder',
# ]

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
